layout_spectrum: 0.8368476943578571
typography_spectrum: 0.9809250037651509
color:
  brandStrength: 0.35345494537614286
  lightness: 0.8866517767310143
  saturation: 0.2607139789033681
  rhythmicContrast: 0.8753440219443291
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
name: Sri Swami Adi Narayan
navigation:
  - name: About
    id: 504ec7fc-5b8d-4441-9725-e7ce5122db25
    type: content
  - name: Blessings
    id: ccafa489-9e46-4967-82dc-4536e1988d4e
    type: content
  - name: Testimonials
    id: ac1c3f01-2af2-4430-bcdb-06667f7c2911
    type: content
  - name: The Beloved
    id: 5b57461e-d796-4e5b-9bf8-867014427ee8
    type: content
  - name: Contact Us
    url: 'http://www.emailmeform.com/builder/form/d2dRb1920BT580rH8X'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/648dee88-7143-46f3-9e7b-6c9fa8574089.jpg
title: ''
description: '"I passed through nothingness, and came back for love."'
