typography_spectrum: 0.5133791659027338
color:
  brandStrength: 0.17866795812733471
  lightness: 0.6040168302133679
  saturation: 0.23958262335509062
  rhythmicContrast: 0.7619681125506759
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.03679013694636524
name: Sri Swami Adi Narayan
navigation:
  - name: Contact Us
    url: 'http://www.emailmeform.com/builder/form/d2dRb1920BT580rH8X'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/648dee88-7143-46f3-9e7b-6c9fa8574089.jpg
title: '"I passed through nothingness, and came back for love."'
